apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
        - name: login-service
          image: your-docker-registry/login-service:latest
          ports:
            - containerPort: 3307
          env:
            - name: PORT
              value: "3307"
            - name: USER_SERVICE
              value: "http://user-service:3306"